### ISSUE TITLE
Dockerfile still references interfaces folder after rename to abi

### ISSUE THREAD

**Issue by arbitrary-cr0** [arbitraryexecution/forta-aave-suite#12]
Looks like we missed a spot during our renaming process. As it stands, the `abi` folder won't get copied during the image build since it's still looking for `interfaces`. 

See:
https://github.com/arbitraryexecution/forta-aave-suite/blob/main/Dockerfile#L17

**Comment by y0wl** [comment]
nice. I think this can be fixed in whichever the next PR that is merged is

**Comment by echoAE** [comment]
Address in pull request: https://github.com/arbitraryexecution/forta-aave-suite/pull/13
